### ISSUE TITLE
Failing to compile after a recent commit

### ISSUE THREAD

**Issue by 0xOmarA** [mozilla/uniffi-rs#1631] opened 2023-07-03 16:06 UTC
I first want to start by thanking the team maintaining UniFFI. I've been looking into this tool for a little over a week now and have been surprised by how capable and how great the generated bindings are. We have faced the same difficulties with code sharing that the various teams over at Mozilla seem to have faced and UniFFI has so far been a pleasure to use! Thank you for writing this tool!

I'm using UniFFI as a git dependency as that's what the UniFFI book [used to recommend](https://github.com/mozilla/uniffi-rs/blob/f0041800c48293d631a2f425861726a5440e245b/docs/manual/src/proc_macro/index.md?plain=1#L15-L17) before the proc-macros feature moved to being non-experimental. More specifically, I'm depending on commit 862e653a9ab8e7b91592fa140cdeb8f1d48a7bb7 of UniFFI-rs.

In my production code I have an enum of 29 variants where each variant has between 2-4 fields each. Some of those fields are of the same data type and some are of differing data types. My enum derives the `uniffi::Enum` trait through UniFFI's `uniffi::Enum` proc-macro. So, I do not have any hand-written definitions in the udl file.

I can generate bindings with no problem when depending on the commit hash 4f39e5d4046d301d75fb4f16457a996bbda05447. However, when updating to f0041800c48293d631a2f425861726a5440e245b, all of a sudden I'm no longer able to compile my Rust crate with the UniFFI API, I get the following error:

```
   Compiling package v0.1.0 (/Users/0xOmarA/Desktop/package)
error[E0080]: evaluation of constant value failed
   --> /Users/0xOmarA/.cargo/git/checkouts/uniffi-rs-6f89edd2a1ffa4bd/f004180/uniffi_core/src/metadata.rs:122:9
    |
122 |         assert!(self.size + other.size <= BUF_SIZE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: self.size + other.size <= BUF_SIZE', /Users/0xOmarA/.cargo/git/checkouts/uniffi-rs-6f89edd2a1ffa4bd/f004180/uniffi_core/src/metadata.rs:122:9
    |
note: inside `MetadataBuffer::concat`
   --> /Users/0xOmarA/.cargo/git/checkouts/uniffi-rs-6f89edd2a1ffa4bd/f004180/uniffi_core/src/metadata.rs:122:9
    |
122 |         assert!(self.size + other.size <= BUF_SIZE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `UNIFFI_META_CONST_PACKAGE_ENUM_INSTRUCTION`
   --> src/lib.rs:4:24
    |
4   | #[derive(Clone, Debug, Enum)]
    |                        ^^^^
    = note: this error originates in the macro `assert` which comes from the expansion of the derive macro `Enum` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant used
 --> src/lib.rs:4:24
  |
4 | #[derive(Clone, Debug, Enum)]
  |                        ^^^^
  |
  = note: this note originates in the derive macro `Enum` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `package` (lib) due to previous error
```

The following is a rather contrived but a minimal example to reproduce this issue. The following code compiles with no issues when depending on commit 4f39e5d4046d301d75fb4f16457a996bbda05447 of the UniFFI crate but does not compile (with the above error) when depending on commit f0041800c48293d631a2f425861726a5440e245b.

```rust
uniffi::include_scaffolding!("package");
use uniffi::{Enum, Record};

#[derive(Clone, Debug, Enum)]
pub enum Instruction {
    CallMethod1 { object: Value, method_name: Value, args: Value },
    CallMethod2 { object: Value, method_name: Value, args: Value },
    CallMethod3 { object: Value, method_name: Value, args: Value },
    CallMethod4 { object: Value, method_name: Value, args: Value },
    CallMethod5 { object: Value, method_name: Value, args: Value },
    CallMethod6 { object: Value, method_name: Value, args: Value },
    CallMethod10 { object: Value, method_name: Value, args: Value },
    CallMethod11 { object: Value, method_name: Value, args: Value },
    CallMethod12 { object: Value, method_name: Value, args: Value },
    CallMethod13 { object: Value, method_name: Value, args: Value },
    CallMethod14 { object: Value, method_name: Value, args: Value },
    CallMethod15 { object: Value, method_name: Value, args: Value },
    CallMethod16 { object: Value, method_name: Value, args: Value },
    CallMethod17 { object: Value, method_name: Value, args: Value },
    CallMethod18 { object: Value, method_name: Value, args: Value },
    CallMethod19 { object: Value, method_name: Value, args: Value },
    CallMethod20 { object: Value, method_name: Value, args: Value },
    CallMethod21 { object: Value, method_name: Value, args: Value },
    CallMethod22 { object: Value, method_name: Value, args: Value },
    CallMethod23 { object: Value, method_name: Value, args: Value },
    CallMethod24 { object: Value, method_name: Value, args: Value },
    CallMethod25 { object: Value, method_name: Value, args: Value },
    CallMethod26 { object: Value, method_name: Value, args: Value },
    CallMethod27 { object: Value, method_name: Value, args: Value },
}

#[derive(Clone, Debug, Enum)]
pub enum Value {
    String { value: String },
    Bool { value: bool },

    U8 { value: u8 },
    U16 { value: u16 },
    U32 { value: u32 },
    U64 { value: u64 },

    I8 { value: i8 },
    I16 { value: i16 },
    I32 { value: i32 },
    I64 { value: i64 },

    Enum { discriminator: u8, fields: Vec<Value> },
    NonHomogenousCollection { elements: Vec<Value> },
    HomogenousCollection { elements: Vec<Value> },
    Map { entries: Vec<MapEntry> },

    PublicKey { value: Vec<u8> },

    Signature { value: Vec<u8> },
}

#[derive(Clone, Debug, Record)]
pub struct MapEntry {
    pub key: Value,
    pub value: Value,
}
```

I think that there are a few ways around this:

1. The `BUF_SIZE` used in the `MetadataBuffer` could be increased to be double what it is now. From my understanding of the architecture of UniFFI, this would not have any impact on the performance of the generated bindings, however, please correct me if I'm wrong about that.
2. A more optimized way of serializing the metadata could be engineered such that types are written to the metadata only once no matter how often they're encountered.
3. Define large enums and types all in the UDL file, which I imagine would not have this issue. 

I believe that option 2 might be the most optimal long term solution, but perhaps option 1 is acceptable in the short term. I've forked the repo and increased the `BUF_SIZE` and was able to get my application compiling with no issues. Would the team be okay with increasing the `BUF_SIZE`, perhaps doubling it?

**Comment by mhammond** [comment] 2023-07-04 13:51
Glad you are enjoying UniFFI!

> A more optimized way of serializing the metadata could be engineered such that types are written to the metadata only once no matter how often they're encountered.

It's not obvious to me how we would do this - we already do arrange for a "type" to be written only once, however enum variants aren't "types" from UniFFI's POV. There might be an optimization we could make specifically for variant types, but it's really not clear how often these are identical like your example.

> Define large enums and types all in the UDL file, which I imagine would not have this issue.

That's probably true today but may not be true forever - I can imagine a world where UDL also writes metadata to the library, which would mean that the UDL file would not be needed at bindings generation time, which would be a big advantage in some cases (ie, needing just the binary to generate foreign code could make some build chains much easier to work with)

> The BUF_SIZE used in the MetadataBuffer could be increased to be double what it is now. 

Given the comments around that constant, it appears this would be fine and have no impact on the generated code. It looks like it would also be possible to have a growable buffer which could actually save memory in the general case (ie, the buffer could start much smaller, and most cases would still avoid allocating to grow it). I doubt that's worthwhile, but maybe give it a few days to see if @jplatte has any thoughts (I think he wrote all that)

**Comment by jplatte** [comment] 2023-07-04 13:58
Nope, I didn't write the `const`-based metadata encoding scheme. That was @bendk :)

**Comment by bendk** [comment] 2023-07-04 14:11
> The BUF_SIZE used in the MetadataBuffer could be increased to be double what it is now.

The issue is that this is a constant used for all the metadata symbols.  So increasing the size would increase the size of the shared libraries, proportional to the number of metadata items which is something like the number of types plus the number of functions exported.  Maybe this is okay though and we could also implement a method for stripping those metadata symbols out after you've generated the bindings which would make this a non issue.

> There might be an optimization we could make specifically for variant types ...

This could be a good workaround for now.  We could make each variant a separate metadata item, so that the `BUF_SIZE` limit applied per-variant rather for the entire enum.  This would also increase the binary size but I think it would be a lot less.

**Comment by mhammond** [comment] 2023-07-04 14:32
> The issue is that this is a constant used for all the metadata symbols. So increasing the size would increase the size of the shared libraries,

The [comments around that const](https://github.com/mozilla/uniffi-rs/blob/044b85dcddd4b4fbd94eb076c8b01c19fa73ac99/uniffi_core/src/metadata.rs#L96-L99) appear to state the opposite though?

**Comment by bendk** [comment] 2023-07-04 15:13
> The [comments around that const](https://github.com/mozilla/uniffi-rs/blob/044b85dcddd4b4fbd94eb076c8b01c19fa73ac99/uniffi_core/src/metadata.rs#L96-L99) appear to state the opposite though?

Yes they do.  I was confused today, sorry about that.  Seems like just bumping `BUF_SIZE` should be perfectly fine.

**Comment by 0xOmarA** [comment] 2023-07-05 05:38
> It's not obvious to me how we would do this - we already do arrange for a "type" to be written only once, however enum variants aren't "types" from UniFFI's POV. There might be an optimization we could make specifically for variant types, but it's really not clear how often these are identical like your example.

What I had in mind was the following: instead of writing the full type id metadata to the metadata buffer (which seems to be the main thing that takes up the most space in the buffer) we could write the hash of the type id metadata or some other kind of a unique identifier. We could then have a map which maps the hash or unique identifier to the type id metadata. This would allow us to not write the type id metadata multiple times, only a hash or unique identifier of it which could be much shorter for complex types.

> Yes they do. I was confused today, sorry about that. Seems like just bumping BUF_SIZE should be perfectly fine.

Fantastic, bumping the buffer size works for me!

**Comment by bendk** [comment] 2023-07-05 13:29
Fixed by https://github.com/mozilla/uniffi-rs/pull/1636

**Closed by bendk** 2023-07-05 13:29 UTC
