### ISSUE TITLE
error calling from Swift: `there is no reactor running, must be called from the context of a Tokio 1.x runtime`

### ISSUE THREAD

**Issue by setoelkahfi** [mozilla/uniffi-rs#2223] opened 2024-08-27 19:54 UTC
There's no mention of providing our asynchronous runtime when trying to expose `async` `throwing` function. But I got this error with this simple example:

```rust

#[derive(Debug)]
enum ErrorResponseV2 {
  Unknown { error_code: i32, message: String },
}

impl Error for ErrorResponseV2 {}

impl Display for ErrorResponseV2 {
  fn fmt(&self, f: &mut Formatter) -> fmt::Result {
    write!(f, "{:?}", self)
  }
}

async fn content_home() -> Result<u64, ErrorResponseV2> {
  match carousel().await {
    Ok(_) => Ok(200),
    Err(_) => Err(ErrorResponseV2::Unknown { error_code: 400, message: "Error".to_string() }),
  }
}

include_scaffolding!("lib");
```

The carousel() function is a wrapper around `reqwest` that calls a REST API endpoint.

UDL file:
```udl
namespace crate_networking {
  [Throws=ErrorResponseV2, Async]
  u64 content_home();
};

[Error]
enum ErrorResponseV2 {
  "Unknown",
};
```

Call from Swift:
```swift
        func viewDidLoad() {
          super.viewDidLoad()
          Task { @MainActor in
            let result = try? await contentHome()
            print(result ?? "")
          }
        }
```
Any clue?

**Comment by mhammond** [comment] 2024-08-27 20:46
The problem appears to be that your `carousel()` call expects a tokio runtime, and as you saw in the linked issue, you can't currently specify that in UDL. If your async function instead used plain futures, I think it would work. So yeah, this is a dupe of #2219 and you probably need to expose that function using procmacros.

**Closed by mhammond** 2024-08-27 20:46 UTC

**Comment by jplatte** [comment] 2024-08-27 22:09
… or do what the proc-macros do when specifying `async_runtime = "tokio"` and wrap the actual async work in [`async_compat::Compat`](https://docs.rs/async-compat/latest/async_compat/struct.Compat.html#method.new).

**Comment by setoelkahfi** [comment] 2024-08-28 06:33
I initially thought the the `uniffii-rs `would look at the `reqwest` implementation and pick up the async runtime automatically.
