### ISSUE TITLE
Errors declared in external crate can't be thrown.

### ISSUE THREAD

**Issue by LBeernaertProton** [mozilla/uniffi-rs#2027] opened 2024-03-12 08:11 UTC
Tested on uniffi v0.26.1.

When attempting to throw an Uniffi Error exported from another crate generating the bindings fails with `Unknown throw type`.

### Example 

Crate A

```
#[derive(uniffi::Error)]
pub enum Error {
     MyError1, 
     MyError2,
}
```

Crate B 

```
#[uniffi::export]
pub fn do_thing() -> Result<(), crate_a::Error> {
    todo!()
}
```

**Comment by mhammond** [comment] 2024-03-12 13:02
Dupe of #1605

**Closed by mhammond** 2024-03-12 13:02 UTC
