### ISSUE TITLE
Prototype bindings for Firefox Desktop front-end (JS) consumers

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#11] opened 2020-06-26 22:43 UTC
We currently have bindings for Kotlin and Python, with Swift in progress. It would be wonderful to generate them for Desktop, too. There are a couple of uniquely Desktop (mostly in the jeez-this-is-clunky sense 😅) things to think about, so let's use this issue to plan out how to do this.

Our current approach is to consume the component's Rust API, and hand-roll a Rust XPCOM wrapper around it, so that JS can call it. This was a quick way to ship our first components. Unfortunately it has a few downsides:

* It makes reasoning about the system harder, since our other bindings go through the same FFI.
* We have to write the FFI ayer twice: once for mobile, and once for Desktop, with XPIDL playing the same role as the C FFI.
* As part of that, we have to reinvent serialization, exchanging objects between Rust and JS by serializing them to JSON, since vanilla XPIDL doesn't do well with complex structures. The FFI handles this for us with JSON and Protobufs.
* It's not particularly ergonomic to work with from either JS or Rust. On the Rust side, there's lots of [clownshoes](https://phabricator.services.mozilla.com/D67075?id=245364#inline-398863) just to do something as common as "calling a method that returns something". On the JS side, we almost always need a `.jsm` wrapper because using the interface directly is so clunky.

XPIDL does have several escape hatches. Methods can return `Promise`s, instead of having to implement their own callback interfaces. `jsval` and `webidl` types are much easier to use from JS (and C++!) An XPIDL interface that makes heavy use of these can be almost as ergonomic as a WebIDL one.

Unfortunately, Rust XPCOM can't do any of those.

* It can't call into a `nostdcall`, `notxpcom` (these use different calling conventions), or `noscript` method, even if it supports that method's types.
* It can't call a method with a `jsval`, `webidl`, or `native` type. The first two require Rust SpiderMonkey bindings, and the last is C++-only.
* It can't consume or return promises (SpiderMonkey again).
* It can't implement an interface at all that uses any of those features.

Although there are helper crates in the tree to make it easier to use Rust XPCOM, it's not as mature or well-supported as C++ or JS yet 😭

So, what else can we use to talk to Rust from JS? Chrome WebIDL, `js-ctypes`...and XPCOM interfaces implemented in C++. Let's look at that last one a bit closer. Since we're generating code, anyway, why not target C++ instead of Rust?

What if we made a backend that spits out an XPIDL interface and a C++ implementation? It could be async-by-default, using the C++ `TaskQueue` class, the same one we used for `storage.sync` and FxA in Rust. It can return promises, and handle threading for us automatically (ooh, threading is a whole other discussion...let's use another issue for that). It could lower `jsval`s to `RustBuffer`s, pass them over the FFI on a background thread, lift the returned value into another `jsval`, and resolve a promise with it—going through the same flow for calling our Rust component as other FFIs.

What are the other alternatives?

* `chrome-webidl`. Used mostly for hot code. We're [discouraged from using it heavily](https://groups.google.com/g/mozilla.dev.platform/c/ONHBIzzM7WU/m/OBxbKD8BDAAJ), since there is a binary size cost ("A WebIDL method binding can easily cost a kilobyte or more, depending on the number and types of the arguments."), and lots of security semantics that don't really apply for chrome code. Much better integration with JS; easy-ish to call from C++, depending on what you're doing.
* `js-ctypes`. Lotsa sharp edges, but can be used from JS directly, no need for a C++ wrapper. Can [use symbols from libxul](https://bugzilla.mozilla.org/show_bug.cgi?id=763848). Can also be used from a `ChromeWorker` (on a background thread), communicating with the main thread using message passing. Can't be used from existing Firefox C++ components—might be a concern when we Oxidize other components, but perfect for JS-only ones.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1563)

**Comment by thomcc** [comment] 2020-06-27 03:47
So, I know way less about this topic than I'd like, so forgive me if this is a dumb question and there are real reasons for these things instead of just "nobody's done it", but:

Isn't another option that we improve Rust XPCOM to do the things we want here? Although it might be a bit more work, if it's still suitably simple it seems possible that this would be better long term, since other Rust XPCOM users would get access to the more complete functionality, even if they aren't using uniffi.

That said I know fairly little here and so my opinions on this being better than any other choice are quite weakly held.

**Comment by linacambridge** [comment] 2020-06-28 21:15
> Isn't another option that we improve Rust XPCOM to do the things we want here?

It definitely is—and I think the answer is that nobody’s done it. There’s a [meta bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1302212) open for some of those improvements; as a very first step, it would be great to get bugs on file for the others.

> Although it might be a bit more work, if it's still suitably simple it seems possible that this would be better long term...

I’m at the edge of my knowledge with this one, but I got the impression talking to @mystor a year ago (goodness, it’s been a long time!) that it’s not simple 😅 For `jsval`s, we’d need to get `js/rust` linking into `libxul` (I think that’s stalled on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1414871), but we can talk with the SpiderMonkey team and resurrect it), and teach the Rust bindings about the event loop for promises—I don’t know what all is involved there. [This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1231711#c6) about WebIDL support in Rust was from three years ago, suggesting being able to pass `webidl` types is even further out, and I don’t think the situation has changed a lot since then.

I completely agree with you, though—it would be a boon for other users of Rust XPCOM!

What I’d really love (of course!) is for Someone Else to do all the hard work of bringing it up to snuff, and we could take advantage of that along with everyone else 😉

**Comment by linacambridge** [comment] 2020-07-09 04:19
I've been looking into this more over the last week, and wanted to share some updates!

Nika and I had a chat, and she suggested it would be easier for us to work with C++, given that we're already generating a C FFI for Swift and Kotlin, and it's unlikely that we'll ever have Rust XPCOM with the full power of C++. Her main goal for Rust XPCOM was letting Rust code access existing C++ interfaces; implementing interfaces in Rust came second. That's not to say we should give up on Rust XPCOM, but I don't think improving it is something for our team to take on. Maybe we can lean on some of the wonderful Oxidation 2020 work from the low-level tools team? 😊

With that in mind, I dug a bit more into how we might generate bindings for Gecko.

# XPIDL interfaces for classes; `webidl` dictionaries for records

To recap, we have two kinds of aggregate types: records and classes. Records are property bags that are passed around by value; classes are passed around by reference, and can have both properties and methods. These map pretty cleanly onto dictionaries and interfaces, respectively, in WebIDL.

We've been encouraged to [avoid WebIDL in favor of XPIDL](https://groups.google.com/g/mozilla.dev.platform/c/ONHBIzzM7WU) for non-hot code, since there is a compile time and binary size cost for WebIDL bindings—sometimes on the order of a kilobyte per method. XPIDL is cruftier, especially when it comes to complex types, and the interfaces don't feel very JavaScript-y...but there are a few things we can do to make it work for us. Specifically, XPIDL methods can take and return WebIDL types (including promises!), and there's a `jsval` escape hatch for anything complicated. `webidl` types can also be attributes.

It sounds like using WebIDL dictionaries with XPIDL is [totally fine](https://bugzilla.mozilla.org/show_bug.cgi?id=1651223#c1), so we could turn a UniFFI interface like [`sprites.idl`](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/examples/sprites/src/sprites.idl) into something like this:

```webidl
// The WebIDL pieces, inside `chrome-webidl/Dictionaries.webidl`.
dictionary Point {
  double x;
  double y;
};

dictionary Vector {
  double dx;
  double dy;
};
```

```idl
// The XPIDL pieces, inside `foo/bar/mozISprites.idl`.
webidl Point;
webidl Vector;

[scriptable, builtinclass, uuid(OMG-NINETIES-IDL-AAAA)]
interface mozISprite : nsISupports {
  void init(in Point initialPosition);
  Point getPosition();
  void moveTo(in Point position);
  void moveBy(in Vector direction);
};

// In WebIDL, we could do `[ChromeOnly, Exposed=Window]`, and expose free
// functions directly on the global scope. In XPIDL, we'll need an extra
// interface to hold them, so that's why this exists. The name could be
// configured as part of the Askama template.
[scriptable, builtinclass, uuid(WHY-IS-THIS-AN-IFACE)]
interface mozISpritesNamespace : nsISupports {
  Point translate(in Point position, in Vector direction);
};
```

(I'm ignoring async for now for this case, and returning promises for blocking tasks dispatched to a background thread. That's a whole 'nother 🥫 of 🐛 for later! But you can imagine, say, an `async` annotation that we use to generate that code in Desktop).

Some things to keep in mind:

* WebIDL and XPIDL represent types differently. Some are just spelling differences (`ByteString` vs. `ACString`); others are deeper (`(ArrayBufferView or ArrayBuffer)?` becomes `Optional<ArrayBufferViewOrArrayBuffer>` in C++—each union gets its own unique type, but would probably be represented as a `jsval` in XPIDL).
* XPIDL interfaces don't have constructors. The convention is to define an `init` method, and have the other methods throw if the method isn't initialized.
* XPIDL interface implementations need a contract ID and a `components.conf` declaration. We can autogenerate these, with instructions for folks to copy-paste them in the right place when working in Firefox.
* We can probably come up with a fancy `mach` integration, so you don't have to copy-paste.
* Any changes to the FFI or Rust component mean we have to revendor and do a full build of Firefox. This makes the local development workflow pretty cumbersome.

# Thin XPIDL interface for the namespace, `jsval`s for everything else

I didn't think about it too seriously, but, since we're writing our code mostly for JavaScript, what if we (ab)used `jsval`s for everything? So we'd only have our "namespace" interface, and expose the `Sprite` class constructor as a `jsval`.

```idl
[scriptable, builtinclass, uuid(OMG-THIS-IS-CLUNKY)]
interface mozISpritesNamespace : nsISupports {
  // Could also use `webidl` types like above, and only use raw `jsval`s for classes.
  jsval translate(in jsval position, in jsval direction);
  readonly attribute jsval Sprite;
};
```

There are lots of drawbacks, which is why I didn't think too hard about it:

* We have to use [JSAPI](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_User_Guide), the C++ interface to SpiderMonkey, to define the constructor and every property and method on those classes.
* JSAPI takes some careful error handling—see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1205137#c22) and [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1496249). Forgetting a null check, or failing to bubble up errors, causes Bad Things to happen. The WebIDL bindings code takes care of that under the hood for dictionaries and interfaces; we'd essentially be doing the same thing.
* It's a lot of code! [This](https://searchfox.org/mozilla-central/rev/7ec7ee4a9bde171ba195ab46ed6077e4baaef34d/toolkit/components/telemetry/core/TelemetryHistogram.cpp#782-858) is what telemetry has to do to expose histogram objects to JS. The binary size would likely be much bigger than defining XPIDL methods.
* The pattern of exposing JS constructors on XPIDL interfaces isn't really common. [Fluent](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/toolkit/components/mozintl/mozIMozIntl.idl#81-85) does this, but check out what it has to do [under](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/toolkit/components/mozintl/MozIntlHelper.cpp#59-80) [the](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/js/src/builtin/intl/DateTimeFormat.cpp#212-248) [hood](https://searchfox.org/mozilla-central/rev/91d82d7cbf05a71954dfa49d0e43824c7c973e62/js/src/builtin/intl/DateTimeFormat.cpp#82-111) to make that work.
* This API is basically unusable from C++. This is last on the list, because we probably won't use the XPIDL API for C++, anyway. It can either use the C FFI directly, or we can generate a [more idiomatic](https://hsivonen.fi/modern-cpp-in-rust/) C++ API. Except for Places, I don't think any of our other components need to be accessed from C++.

But, this would make using the API from JS easier. Consuming code would only need to import the constructor like `const Sprite = Cc["..."].getService(Ci.mozISpritesNamespace).Sprite`, and then it could write `new Sprite(...)` and such, without involving XPIDL at all. We would generate getters and setters for class properties, and wouldn't need to lower them into XPIDL and WebIDL like with option 1.

Which got me thinking...

# `js-ctypes`

Why not lower our API into a worker, . I didn't give it much thought before, but a few things about it are attractive at first glance:

* "It's just JavaScript". We can play with making a more idiomatic API without having to rebuild all of Firefox, or write scary-looking Gecko C++. We only have to lower types to JS.
* It can be used in a [`ChromeWorker`](https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Chrome/API/ChromeWorker), meaning we can call into blocking FFI functions directly from the worker, then use a [`PromiseWorker`](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/toolkit/components/promiseworker/PromiseWorker.jsm#5-16) to get async "for free".
* It can load symbols from any library, not just `libxul`. So our development workflow gets _so much_ easier: we can run `cargo build` to make a `dylib`, then point the JS wrapper to it, and work in an artifact build of Firefox. That's amazing! With Rust and C++, as soon as you want to change anything, you have to do a full build. We could even package and ship `libmegazord` with Firefox, like we do for our other platforms.
* The generated bindings end up looking a lot like the Python ones, which use Python's `ctypes`.

There are lots of downsides, though:

* It's [veeeeryyy](https://bugzilla.mozilla.org/show_bug.cgi?id=640024) [sloooowwww](https://bugzilla.mozilla.org/show_bug.cgi?id=873307).
* Going through a `ChromeWorker` will add even more overhead. `osfile.jsm` is getting a [rewrite in C++](https://bugzilla.mozilla.org/show_bug.cgi?id=1231711) for performance.
* Packaging `libmegazord` as-is probably won't work, since we'd be shipping a second copy of the Rust runtime, SQLite, and many of the same dependencies as `libxul`. It'll also bump the installer size. But, we can still have a `libmegazord` workflow for local dev, then smoosh everything into `libxul` (our [LZ4 bindings](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/toolkit/components/lz4/lz4_internal.js#30,33-64) do something like that) for pushes to m-c.
* It's not maintained. There's a [long bug backlog](https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=js-ctypes&bug_status=__open__). It breaks on [new](https://bugzilla.mozilla.org/show_bug.cgi?id=1648352 [platforms](https://bugzilla.mozilla.org/show_bug.cgi?id=1480548#c2).
* There's [memory unsafety](https://bugzilla.mozilla.org/show_bug.cgi?id=627107) and [inefficiencies](https://bugzilla.mozilla.org/show_bug.cgi?id=552070) in the implementation.
* No compile-time checking for method signatures. I think JNA shares this to some extent, but the interface exposed to Kotlin is type safe. `js-ctypes` will happily let you import nonexistent functions and call them with the wrong arguments, and presto, down comes Firefox!

My overall impression of `ctypes` was, it gives you the [type safety of JS, the speed of Smalltalk, and the memory safety of C](http://james-iry.blogspot.com/2009/05/brief-incomplete-and-mostly-wrong.html). If we're going this route, we might want to explore Wasm more.

But it's about the end of my day, so I'll leave this here, and write more about Wasm later! 😁

**Comment by linacambridge** [comment] 2020-07-09 04:36
The Wasm TL;DR is: it's cool, it's fast, we already have [uses](https://github.com/mstange/profiler-get-symbols) of it [in m-c](https://searchfox.org/mozilla-central/rev/85ae3b911d5fcabd38ef315725df32e25edef83b/toolkit/components/extensions/ProfilerGetSymbols-worker.js), and it's a match made in heaven for Rust!

But we really need filesystem (and network, for `sync15` and the FxA client) access, and Wasm is sandboxed by design 😭

**Comment by rfk** [comment] 2020-07-11 11:24
> But we really need filesystem (and network, for sync15 and the FxA client) access, and Wasm is sandboxed by design 😭

The WASI stuff is supposed to give us some of that for free IIUC, but I won't be surprised to hear that nobody was integrated any of WASI into Firefox yet because all of the *in Firefox* uses of WASM are heavily sandboxed by design.

**Comment by linacambridge** [comment] 2020-08-20 03:51
I started hacking on this over in the [gecko](https://github.com/mozilla/uniffi-rs/tree/gecko) branch, and wanted to share a couple of updates!

Type conversions and the  `RustBuffer` helpers are mostly done! For now, I've been hacking on them in a throwaway C++ header file with a few stubs in my local m-c tree, and periodically copy-pasting that into the `Detail.cpp` template 😬 It's sooo janky, but it works, and the compiler can help me out with all the Gecko types. The helpers compile now, but this is C++, so I bet there are a few surprise `panic!`s at the disco hiding in that code.

The next step is to finish up WebIDL code generation. At first, I was thinking of generating hybrid WebIDL and XPIDL bindings: using WebIDL for dictionaries and enums, and XPIDL for top-level functions and objects. But that's pretty involved, and juggling types between XPIDL, WebIDL, the FFI, and the C++ implementation quickly turned into a rabbit hole. XPIDL types are just too limited for what we want—for example, there's no way to encode nullability in the type; we'd need to use something like `nsIVariant` and generate some runtime type conversions. WebIDL, on the other hand, gives us a rich type system that makes code generation and interfacing with C++ much easier. There are a lot of things left to do in the prototype, so I think it would be better to focus on just generating a Gecko `[ChromeOnly]` WebIDL binding.

Arguments and return values are a little more involved for WebIDL—some of them are returned as out-params and others as return values, different types for the same thing (a `sequence` can either be a `mozilla::dom::Sequence` or an `nsTArray`, depending on where it is)—but tractable.

(Side note: @vladikoff mentioned we might have in-tree C++ consumers, too, not just JS. This would be a pretty easy addition, which I'm excited about! 😁 We can reuse the same seralization helpers for all of them, and write a nice C++ interface on top, with signatures like `MyCoolObject(Maybe<Something>&, nsTArray<AnotherCoolType>)` instead of `Constructor(dom::GlobalObject&, dom::Nullable<Something>&, dom::Sequence<OwningNonNull<AnotherCoolType>>, ErrorResult&)`.

After getting WebIDL generation in place, I'd love to get a basic demo with arithmetic working in Firefox! That will involve:

- [ ] Linking `uniffi-example-arithmetic` into libxul, and making sure its `build.rs` runs as part of the Firefox build to generate the UniFFI scaffolding. This should make its FFI symbols available.
- [ ] Generating the Gecko bindings, and dropping them into `chrome-webidl` and the implementation somewhere else. There might be some config files we have to tweak in addition to `moz.build`.
- [ ] Adding an xpcshell test for the new binding!
- [ ] Fixing all the crashes in the C++ code 😭 

In terms of the consumer experience...it would be super cool to eventually automate the entire binding generation process (maybe "all" we have to do is teach the WebIDL code generator to look for `[ChromeOnly]` bindings in the UniFFI target dir, and build the C++ implementation that comes with them?). XPIDL would complicate things—we'd have to generate XPTs, and, if any of our WebIDL types use XPIDL ones, we have to add them as external interfaces—but I don't want to worry about that just yet. For now, I think manually generating the Gecko bindings and copy-pasting them into the tree is totally fine.

**Comment by linacambridge** [comment] 2020-08-27 04:07
There's a draft of this over in #255 now. Let's keep this ticket open for more discussion, and use the PR for reviews.

**Comment by linacambridge** [comment] 2020-09-10 20:58
Morphing this ticket to cover bindings for front-end consumers, since that’s what #255 does. #269 is about platform consumers. To recap:

* Front-end consumers are written in JS. Firefox Desktop has a few ways for JS code to call into Rust—WebIDL, XPIDL, `js-ctypes`, and Wasm. Both WebIDL and XPIDL require us to generate a pile of C++ glue code that connects the interface to the Rust component.
* Platform consumers are written in C++. The language bindings that we generate for these can just be a `.h`/`.cpp` pair; no need for IDLs.

They are related (both involve generating C++ code), but separate (you can generate just front-end bindings, just platform bindings, or both for a component; think of them as different language backends).

**Comment by data-sync-user** [comment] 2020-09-10 21:40
➤ Lina Cambridge commented:

Following up again from our sprint planning—since we have a PR with the prototype up, and we have more specific follow-ups filed for Desktop, let's close this out.

**Closed** 2020-09-10 21:40 UTC
