### ISSUE TITLE
Seeking clarification on `crate-type` flag

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1566] opened 2023-05-30 18:05 UTC
I'm looking to validate my mental model for the values required in the `crate-type` flag for libraries leveraging uniffi-rs.

Given [this page in the docs](https://mozilla.github.io/uniffi-rs/tutorial/Prerequisites.html#prerequisites), I had been building my bindings with both the `cdylib` and `staticlib` flags in my `Cargo.toml` file like so:
```toml
[lib]
crate-type = ["staticlib", "cdylib"]
```

But yesterday when attempting to build an example of uniffi libraries with dependencies between each other, I ran into issues which were solved by adding the `lib` flag to the previous two (see #1563 and the solution proposed there). I now realize I'm not sure why this is needed in this case, nor when each of them is required if it's platform dependent.

I build bindings for Android, Kotlin/JVM, Swift, and Python. The Python and Kotlin/JVM libraries are meant to run on macOS x86_64 and aarch64 architectures, and linux x86_64. Moreover, we'll be attempting to build uniffi libraries into layers where at least one "core" library will feed into a few user-facing libraries that will depend on it. It seems like the crate-type matters for this, but I'm not sure how.

I'd love to disentangle these crate-type and library requirements in my mind but can't quite find explicit information on this in the docs. My question here is this: what are the different crate-types required for different platforms? Could I create a table that would document those?

Something like this:
| crate-type | Required For |
| -------- | ------- |
| cdylib  | Kotlin/Android |
| staticlib | Swift |
| lib | libs with inter-dependencies? |

Or maybe this:
| Platform | crate-type |
| -------- | ------- |
| Kotlin/Android | `cdylib` |
| Swift/iOS | `staticlib` |
| Kotlin/JVM | ? |
Python | ? |
| libs with inter-dependencies (root) | `lib` |
| libs with inter-dependencies (user of root) | `staticlib`, `cdylib`, `lib` |

Feel free to point me to docs I might have missed if I have. Hopefully the parts of this I'm not quite clear on are laid fairly bare in this long question; if a different frame of mind or mental model is better adapted to understanding the requirements than the tables I added above feel free to reframe my question(s).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-274)
┆Issue Number: UNIFFI-274

**Comment by mhammond** [comment] 2023-05-30 18:46
As the linked issue shows, (uniffi is filtering for explicitly `lib`](https://github.com/mozilla/uniffi-rs/pull/1516/files#diff-a2c8329d265afcb1ea0c4ba6f2ab1bb5cf71ab6be23d2a8a8cdc437adb5ca671R157). I *suspect* that is the bug - eg, if a create is building a final `cdylib` or `staticlib`, it should still be capable of importing other external types and even supplying unresolved ones.

IOW, I think a part of the problem is the lack of examples/test exercising the various ways rust can be packaged rather than an explicit goal/decision to only support certain ways of packaging.

**Comment by thunderbiscuit** [comment] 2023-06-14 14:43
Thanks for the answer Mark! I'm not sure if it's fully clearing it up for me yet though... 

Am I correct in thinking that the `cdylib` and `staticlib` are not required by the uniffi library I'm building as a dependency, and the `rlib` is not required for the final, user-facing library (which will only declare `cdylib` and `staticlib`?

_Edit: Ok maybe I understand better your comment now after from fiddling around with different configurations (the filter is not for the substring `lib` but for the actual string `lib`; I had misread the code linked above). In short, in my mental model the dependency needed only rlib, and the user-facing library only needed cdylib and staticlib, and then you'd move the appropriate binaries to where they needed to go. This is not the case because of the `generate --library` step, which requires `lib` for both. As far as I understand, the final requirements are like so:_
_1. Use `lib` in the root, "dependency" library you will import into your other library._
_2. Use `cdylib`, `staticlib`, and `lib` crate types in the user-facing library._

I agree more examples would be fantastic. We're building something of that sort [in fact right here](https://thunderbiscuit.github.io/uniffi-examples/).

**Comment by thunderbiscuit** [comment] 2023-06-14 14:48
Thanks for the help. Unless I made a mistake above I think I finally grok it, and this issue is ready to be closed.

**Comment by mhammond** [comment] 2023-06-14 15:24
> We're building something of that sort [in fact right here](https://thunderbiscuit.github.io/uniffi-examples/).

That looks great - we'd absolutely love some PRs for docs and examples, especially to clarify various ways things can be packaged. But I'll take your advice and close this for now, thanks!

**Closed by mhammond** 2023-06-14 15:24 UTC
Labels: uniffi
