### ISSUE TITLE
Implement the concurrency-control solution from ADR-0003

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#370] opened 2021-01-14 01:46 UTC
In #368 we are proposing some changes to the way that uniffi handles concurrent access to object instances. That bug is specifically for agreeing on and documenting a plan, so I'm filing here a separate bug to track the work of implementing said plan.

The ADR contains an [implementation sketch](https://github.com/mozilla/uniffi-rs/blob/adr-threadsafe-interface/docs/adr/0003-threadsafe-interfaces.md#implementation-sketch) section with an outline of the work to be done here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2005)

**Comment by rfk** [comment] 2021-01-14 01:47
@jhugman volunteered to take a look at the implementation work here, so I'm optimistically assigning him this issue.

**Comment by data-sync-user** [comment] 2021-01-14 22:43
➤ Janet Dragojevic commented:

closing in favor of SDK-170

**Comment by data-sync-user** [comment] 2021-01-14 22:44
➤ Ryan Kelly commented:

Closing as a dupe of https://jira.mozilla.com/browse/SDK-170

**Closed** 2021-01-14 22:43 UTC
